### PR TITLE
Draft Example data sets

### PR DESCRIPTION
**Pull request by bailliem**
I have added a [draft data set](https://github.com/VIS-SIG/Wonderful-Wednesdays/tree/master/data/2020/2020-04-08) (ADTTE again) I simulated a while ago. This time ADTTE is based on a trial in breast cancer comparing 4 different treatment regimens. See [here](https://github.com/VIS-SIG/Wonderful-Wednesdays/tree/master/data/2020/2020-04-08) for background. 

```
library(ggsurvfit)
library(ggplot2)
p <- ADTTE %>%  survfit2(Surv(AVAL, 1-CNSR) ~ TRT01P, data = .) %>%
  ggsurvfit() +
  add_censor_mark() +
  add_confidence_interval() 

p
p + add_risktable()
```

image

image

It does provide challenges with the treatment labels and the number of arms. The treatment labels, etc. could all be edited.  

## The data set and variable definitions

The data set is an abridged version of the [CDISC
ADaM](https://www.cdisc.org/standards/foundational/adam)
[ADTTE](https://www.cdisc.org/system/files/all/standard_category/application/pdf/adam_tte_final_v1.pdf)
time to event data set.

The data set contains the following variables:

  - STUDYID - the study identifier
  - SUBJID - subject identifier
  - USUBJID - unique subject iddentifier
  - AGE - age at randomisation (years)
  - STR01 - Hormone receptor status at randomisation
  - STR01N - Hormone receptor positive (Numeric)
  - STR01L - Hormone receptor positive (Long format)
  - STR02 - Prior Radiotherapy at randomisation
  - STR02N - Prior Radiotherapy at randomisation (Numeric)
  - STR02L - Prior Radiotherapy at randomisation (Long format)
  - TRT01P - Planned treatment assigned at randomisation
  - TRT01PN - Planned treatment assigned at randomisation (Numeric)
  - PARAM - Analysis parameter - Progression free survival
  - PARAMCD - Analysis parameter code
  - AVAL - Analysis value (time to event \[days\])
  - CNSR - Censoring (0 = Event, 1 = censored)
  - EVNTDESC - Event description
  - CNSDTDSC - Censoring description
  - DCTREAS - Discontinuation from study reason

A number of baseline measurements are also included such as age, hormone
receptor status and prior radiotherapy treatment. Additional details on
reasons for study discontinuation and censoring event description are
also included.

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Fantastic! I'm working on a theme that replaces the strata labels with a block of color in the risk tables. I think that will alleviate many of the concerns from long labels.

I think I've found a solution (somewhat fiddly), and it needs testing to see how it holds up against users' customizations....

**Review by ddsjoberg — CHANGES_REQUESTED** [review]
This will be a great addition.
- [x]  can you add column labels to the data frame?
- [x] the data set needs to be documented in the `R/data.R` file.
- [x] do you think it would be worth it to include the simulation code in `data-raw/DATASETS.R` ?

**Comment by ddsjoberg** [comment]
@bailliem how do you want to deal with the CNSR coding in this dataset? Just pass `Surv(AVAL, 1 - CNSR)`?

**Comment by bailliem** [comment]
> @bailliem how do you want to deal with the CNSR coding in this dataset? Just pass `Surv(AVAL, 1 - CNSR)`?

I think so for now. Could also have an example which demostrates the Surv_CNSR function. But to be discussed..

**Comment by bailliem** [comment]
> This will be a great addition.
> 
> * [x]   can you add column labels to the data frame?
> * [x]  the data set needs to be documented in the `R/data.R` file.
> * [x]  do you think it would be worth it to include the simulation code in `data-raw/DATASETS.R` ?

ping - can you take a look now. Source data is in there but sharing simulation code may be tricky.

**Pull request merged**
